src/PackagerNewCommand.php

`composer.json` contained a bunch of unreplaced placeholders. Not sure how that package could have worked for you guys in the last few months, but from what I can see the placeholders were changed on Nov 27, 2015
https://github.com/thephpleague/skeleton/commit/d048eb97f87bb2546f1444528a75d109b70ae2e8

use correct placeholders of league skeleton

---

readme.md

`$ php artisan packager:new MyVendor MyPackage -i` should read `$ php artisan packager:new MyVendor MyPackage --i`

Fixes typo for interactive packages

---

src/PackagerListCommand.php

[ErrorException] Undefined variable: packages when trying to run “php artisan packager:list”

Fix undefined $packages variable

---

src/PackagerTestsCommand.php

The getcwd() function did not work for me on Windows. I just changed the path variable to make it work.

packager:tests command not working on Windows

---

readme.md

Adding `--dev` param to composer require as per https://github.com/Jeroen-G/laravel-packager/issues/54#issuecomment-412326270 discussion.
Installing only on development will avoid extra deploy latency/overhead in production, reduce risk and avoid issues loading service provider as it's not autodiscovered if it's not installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jeroen-g/laravel-packager/55)

Add --dev param to composer require

---

src/Commands/GitPackage.php

This PR adds functionality to check if the `git clone` step was successful.
A check for the exit code from the `exec()` function has now been added if there are any failures (authentication, does not exist etc). In the event the `git clone` was not successful, the script prints a error message and exits.
'packages/' folder (and additional folders) will not be created, and both `config/app.php & `composer.json` files will not be updated.
A new `setGitVendorAndPackage()` method has been added to the class. This replaces the previous code and now checks if the url passes contains `https`. If it doesnt, it will assume the `ssh` version was used (e.g. `git@github.com:Jeroen-G/laravel-packager.git`).
**Note:** The creation of the `packages` step has been removed, I found this was no required …

Will check if git clone was successful

---

src/Commands/GitPackage.php
src/Wrapping.php

Closes #71, Closes #65.
This formats the `vendor` and `package` when using the `php artisan packager:git` command.
Using  `->formatVars()` method, both are changed to title case. If there are any hyphens, the string is split, changed to title case and concatenated.

Convert vendor and package to camel case when installing package from git

---

.gitignore
composer.json
readme.md
src/Commands/DisablePackage.php
src/Commands/EnablePackage.php
src/Commands/GetPackage.php
src/Commands/GitPackage.php
src/Commands/ListPackages.php
src/Commands/NewPackage.php
src/Commands/RemovePackage.php
src/Conveyor.php
tests/IntegratedTest.php
tests/TestCase.php
tests/TestHelper.php

Hi, thanks for an excellent package.
I've made a few changes that I think makes the workflow a bit simpler and more intuitive.
By using path repositories in the parent project, the packages can be installed exactly like any other package.
Here are the benefits as I see them:
- No need to install/update dependencies in the package sub-folders. Everything is managed from the project root.
- Service providers are discovered automatically during installation.
- Classes in the package namespaces are autoloaded automatically just like any other package.
- Having only one `vendor/` folder means no duplicate dependencies, which tend to confuse IDEs like PhpStorm.
Let me know if anything needs to be changed.

Use Composer path repositories to install packages in parent project.

---

src/ArchiveExtractors/Extractor.php
src/ArchiveExtractors/Manager.php
src/ArchiveExtractors/Tar.php
src/ArchiveExtractors/TarGz.php
src/ArchiveExtractors/Zip.php
src/Conveyor.php
src/FileHandler.php
src/PackagerServiceProvider.php
tests/SkeletonArchiveExtractorsTest.php
tests/TestTarGzSkeletonArchive.php

- Added `tar` and `tar.gz` skeleton archive support
- Allow to use archives with non-wrapped files (removed hardcoded `packager-skeleton-master` directory)
- Added ability to add custom archive extractors via extractors Manager.
#91

Added ability to use tar and tar.gz or any other skeleton archive format

---

readme.md
src/Commands/NewPackage.php
src/Conveyor.php
tests/IntegratedTest.php

Fixes #104 . Non-breaking change.
Adds an optional ```--skeleton``` flag to the ```new``` command, so that the user can force a certain skeleton to be used, instead of the one in the config file.
Use cases:
```bash
php artisan packager:new MyVendor MyPackage
php artisan packager:new MyVendor MyPackage --i
php artisan packager:new MyVendor MyPackage --skeleton="https://github.com/DigitallyHappy/backpack-operation-skeleton/archive/master.zip"
php artisan packager:new MyVendor MyPackage --i --skeleton="https://github.com/DigitallyHappy/backpack-operation-skeleton/archive/master.zip"
```
One thing I'm not 100% happy with - the unit test doesn't _actually_ test that it's using a _different_ Skeleton. Because I assume you want a skeleton that _you_ own in the tests. In order to better test …

Added skeleton flag to new command

---

readme.md

The extra "]" leads to a dead link. This PR fixes the typo.

Fix link to contributors (typo)

---

changelog.md
src/Commands/GitPackage.php
src/Conveyor.php
tests/IntegratedTest.php

Me again... :)
When `prefer-stable` is `true` in your project's `composer.json`, Composer will get the package from packagist and install it, he will not care about your local package, in spite of the fact that there is a repository with a path declared in your `composer.json`.
Example :
```
php artisan packager:git https://github.com/Seldaek/monolog monolog monolog
```
As you can see in your vendor folder, `monolog/monolog` is a folder instead of a symlink to `packages/monolog/monolog`. The version installed come from packagist instead from the local folder.
The solution is to force to use symlink in your composer.json, see [https://getcomposer.org/doc/05-repositories.md#path](https://getcomposer.org/doc/05-repositories.md#path)
But this is not sufficient, you also have to say to …

Use of symlink with existing packages

---

changelog.md
src/Commands/NewPackage.php
src/Conveyor.php
src/FileHandler.php
tests/IntegratedTest.php

Hi!
This PR completes #97 with tests and fix StyleCI issues.
This feature is a must-have, a lot of people use the kebab-case or snake_case as vendor name or package name. 
Without this fix you can't use `packager:new` to create a new package with the default skeleton, it's a pity.
Hope you'll enjoy

Fix vendor-name package-name not converted to studly case

---

composer.json

- Added some test options to the composer `scripts` section
- This allows to run all PHPunit tests using `composer test` to run the full suite. 
- You can also run the PHPunit tests without code coverage report (`composer test-f`) to speed up running the tests. 
- You can also filter down to a specific test using `composer test-f {test name}` or `composer test-coverage-f {test name}`.

Add test scripts to composer file for easy package testing

---

src/Commands/NewPackage.php
src/ValidationRules/ValidClassName.php
tests/IntegratedTest.php

This MR validates all vendor and package names against the regex for valid PHP class names as suggested in #80.
Closes #80 
- Added a custom validator `ValidClassName` which validates an input against a modified regex for valid PHP classnames, which also **allows dashes**, as they are already converted into valid PHP classes. 
- Validate the `vendor` and `name` inputs for the artisan command `packager:new` against this custom validator
- Added PHPunit tests
- Try to create a new package with an invalid vendor name (e.g. `123Vendor`) and assert that an error is shown and no package was created.
- Try to create a new package with an invalid package name (e.g. `123Package`) and assert that an error is shown and no package was created.

Validate package and vendor names for new packages

---

src/FileHandler.php
src/Wrapping.php

When I started I thought of adding a second `rewriteRules.php` file for `replaceRules.php`, it seemed like it was a little too cumbersome. 
Instead this approach uses an itterator and searches anything and everything recusively. It's an optimization for convenience which seems quite "Laravel". It's undoubtedly a little slower but the work is done locally and infrequently. 
Since the last pull request removed the string replace method of updating composer -- <3 -- I'm wondering if using Wrapper.php for content S&R is still a good idea. Maybe these dual directory itterators could be combined to improving the speed.
---
In my skeleton I was looking to move  `src\MyPackageProvider` to `src\Providers\MyPackageProvider` while adding a couple other items. 
Where 4n70w4 in #81 , for a Nova …

Broadening replacements for improved skeleton replacements

---

changelog.md
src/Commands/NewPackage.php
src/Commands/RemovePackage.php

Hi! Me again :)
This PR will fix the remove of non empty vendor directory.
```
php artisan packager:git https://github.com/sebastienheyd/boilerplate
php artisan packager:git https://github.com/sebastienheyd/boilerplate-media-manager
php artisan packager:remove sebastienheyd boilerplate-media-manager
```
The whole folder `packages/sebastienheyd` is deleted instead of only `packages/sebastienheyd/boilerplate-media-manager` when you answer yes to "Do you want to remove the vendor directory?"
A simple check if vendor directory is empty or not, if not a warn appears and the script continue.
https://github.com/sebastienheyd/laravel-packager/blob/ac1cdcf93765b069a5f4f86e00738171c57b2c8c/src/Commands/RemovePackage.php#L92-L97
Like `packager:new` I added the possibility to use `vendor/package` …

Fix remove non-empty vendor directory

---

src/Commands/NewPackage.php
src/Conveyor.php

Provides the functionality suggested in https://github.com/Jeroen-G/laravel-packager/issues/132 .
After this PR, packager skeletons can use two more keywords, and they'll automatically be substituted for the right thing by Packager:
```diff
':uc:vendor', // MyVendorName
':uc:package', // MyPackageName
':lc:vendor', // myvendorname
':lc:package', // mypackagename
+            ':kc:vendor', // my-vendor-name
+            ':kc:package', // my-package-name
```
This PR does NOT make Packager use these new keywords anywhere (by default) - it just adds the functionality for _skeletons_ to include those keywords. If they do, Packager will replace them. 
It just adds a minor functionality, so it's a non-breaking change. I see no reason for it not to be merged & tagged as `2.6.1` - @Jeroen-G if you …

Allow kebab-case to be used for package and vendor names - fixes #132

---

tests/IntegratedTest.php

Two tests were failing:
1. `test_get_existing_package_with_get` was failing because the `monolog` package has changed the primary branch from `master` to `main`; this was an easy fix;
2. `test_new_package_is_created` was failing because it was checking for the symlink (`vendor/myvendor/mypackage`) instead of the actual package directory (`packages/MyVendor/MyPackage`); fixed it by checking the latter instead;
So both tests are now successful.
---
HOWEVER. I did discover this _testing_ problem you might want to know about or address: 
- the symlink DOES get created when running `php artisan packager:new MyVendor MyPackage` from the root project;
- the symlink DOES NOT get created when running the same thing inside the tests;
I tried to understand why that's happening, debugged it for quite …

Fix unit tests

---

config/packager.php
readme.md
src/Commands/NewPackage.php

@Jeroen-G I was working on a PR to your package skeleton, to make it use `kebab-case` by default, as talked about [here](https://github.com/Jeroen-G/laravel-packager/pull/135#issuecomment-782860851). But it turns out... no changes to the package skeleton are really needed 🥳  Turns out switching from StudlyCase to kebab-case is NOT a _functionality_ issue, but a _documentation_ issue. 
This is a long read, so strap in. But that's only because I've tried to be as thorough as possible, and think of all the implications.
Even without PR https://github.com/Jeroen-G/laravel-packager/pull/135 which adds `:kc:vendor:` and `:kc:package:`, there is a VERY easy way to create proper kebab-cased folders & links with your existing package & package-skeleton. By just... using kebab-case as the inputs. I …

document kebab-case as the default way to create packages

---

config/packager.php

- Use `https` instead of `http` for the skeleton url address

Use 'https' instead of 'http' for the skeleton

---

phpunit.xml

- Migrated the PHPUnit XML schema to the new PHPUnit 9.0 configuration, using the `--migrate-configuration` option

Update deprecated PHPUnit XML schema (which is used by PHPUnit 9.0)

---

src/FileHandler.php

Fixes package path in composer.json file.

Close #167
